version: '3'
services:
  db:
    image: postgres
    container_name: panopticum_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: panopticum_user
      POSTGRES_PASSWORD: panopticum_password
      POSTGRES_DB: panopticum_db
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 2s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6000M
        reservations:
          cpus: '1'
          memory: 4000M
  web:
    build: .
    container_name: panopticum_backend
    ports:
      - "8000:8000"
    volumes:
      - ./compose/panopticum/settings_local.py:/opt/panopticum/panopticum_django/settings_local.py:ro
    depends_on:
      init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
        reservations:
          cpus: '1'
          memory: 500M
  nginx:
    image: nginx
    container_name: panopticum_nginx
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - db
  init:
    build: .
    container_name: panopticum_migrate
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
