# Generated by Django 2.1 on 2019-12-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='personrolemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personrolemodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personrolemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='employee_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='office_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panopticum.PersonRoleModel'),
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('simplenamemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panopticum.SimpleNameModel')),
            ],
            bases=('panopticum.simplenamemodel',),
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('simplenamemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panopticum.SimpleNameModel')),
            ],
            bases=('panopticum.simplenamemodel',),
        ),
        migrations.CreateModel(
            name='OrgDepartmentModel',
            fields=[
                ('simplenamemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panopticum.SimpleNameModel')),
            ],
            bases=('panopticum.simplenamemodel',),
        ),
        migrations.AddField(
            model_name='personrolemodel',
            name='simplenamemodel_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panopticum.SimpleNameModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panopticum.CountryModel'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='org_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panopticum.OrgDepartmentModel'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panopticum.OrganizationModel'),
        ),
    ]
