# Generated by Django 2.1.15 on 2020-03-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentRuntimeTypeModel',
            new_name='ComponentTypeModel',
        ),
        migrations.RenameField(
            model_name='componentmodel',
            old_name='runtime_type',
            new_name='type',
        ),
    ]
