# Generated by Django 2.1.15 on 2020-03-16 23:30

from django.db import migrations
import panopticum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0002_auto_20200318_1116')
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkmodel',
            name='notes',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='Framework notes', verbose_name=''),
        ),
    ]
