# Generated by Django 2.1.15 on 2020-03-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0002_auto_20200314_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Runtime: e.g. C++/Python/Go runtime', max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panopticum.ProgrammingLanguageModel')),
            ],
            options={
                'verbose_name': 'Runtime',
                'verbose_name_plural': 'Runtimes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='runtime',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='panopticum.RuntimeModel'),
        ),
    ]
