# Generated by Django 2.1.15 on 2019-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0002_auto_20191219_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
