# Generated by Django 2.1 on 2019-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0002_auto_20191219_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='active_directory_guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
