# Generated by Django 2.1 on 2019-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0003_auto_20191219_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide the person from the potential assignee lists'),
        ),
    ]
