# Generated by Django 2.1.15 on 2020-03-23 10:54

from django.db import migrations, models
import panopticum.fields


class Migration(migrations.Migration):

    replaces = [('panopticum', '0004_auto_20200322_1402'), ('panopticum', '0005_requirementset_doc_link'), ('panopticum', '0006_auto_20200322_2325')]

    dependencies = [
        ('panopticum', '0003_frameworkmodel_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_api_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_manual_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_perf_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_security_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_unit_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_api_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_e2e_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_longhaul_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_manual_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_perf_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_security_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_unit_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AddField(
            model_name='requirementset',
            name='doc_link',
            field=models.URLField(blank=True, max_length=4096, verbose_name='Documentation link URL'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_commit_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_jira_component',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_raml',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_commit_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_jira_component',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_public_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_public_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_raml',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
    ]
