# Generated by Django 2.1.15 on 2020-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0003_auto_20200314_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='is_new_deployment',
            field=models.BooleanField(db_index=True, default=False, help_text='This component is new in given product'),
        ),
    ]
