# Generated by Django 2.1.15 on 2020-03-22 11:02

from django.db import migrations
import panopticum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0003_frameworkmodel_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_api_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_manual_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_perf_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_security_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_unit_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_api_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_e2e_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_longhaul_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_manual_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_perf_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_security_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='qa_unit_tests_status',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', help_text='Subjective Dev/QA lead opinion on tests completeness, coverage, quality, etc', max_length=16, verbose_name=''),
        ),
    ]
