# Generated by Django 2.1.15 on 2020-03-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0004_componentdeploymentmodel_is_new_deployment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentcategorymodel',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='componentmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='panopticum.ComponentCategoryModel'),
        ),
    ]
