# Generated by Django 2.1 on 2019-12-26 23:01

from django.db import migrations, models
import django.db.models.deletion
import panopticum.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0004_personmodel_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDependencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sync_rw', 'Sync R/W'), ('sync_ro', 'Sync R/O'), ('sync_wo', 'Sync W/O'), ('async_rw', 'Async R/W'), ('async_ro', 'Async R/O'), ('async_wo', 'Async W/O')], default='sync_rw', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentDeploymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Component deployment type: Cloud Account Server', max_length=64)),
                ('service_name', models.CharField(blank=True, help_text='accsrv, taskmngr', max_length=64)),
                ('binary_name', models.CharField(blank=True, help_text='accsrv.exe', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEnvironmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='K8S, Windows VM, Linux VM,...', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLocationClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='global, per-datacenter, customer, endpoint', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(help_text='sorting order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='OSFamilyModel',
        ),
        migrations.RemoveField(
            model_name='componentmodel',
            name='datacenter',
        ),
        migrations.RemoveField(
            model_name='componentmodel',
            name='location_class',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='compliance_fips',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='compliance_gdpr',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='dev_api_guideline_compliance',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='dev_autotests_report',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='dev_documentation',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='dev_life_status',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_backup_doc_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_binary_name',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_capacity_doc_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_deployment_name',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_deployment_type',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_guide_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_high_availability',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_metrics',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_open_port',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_sla_doc_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_zero_downtime_upgrade',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_api_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_api_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_manual_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_manual_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_perf_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_perf_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_security_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_security_tests_model',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_unit_tests_link',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='qa_unit_tests_model',
        ),
        migrations.AddField(
            model_name='componentmodel',
            name='life_status',
            field=models.CharField(blank=True, choices=[('unknown', '?'), ('new', 'New'), ('mature', 'Mature'), ('legacy', 'Legacy'), ('eol', 'End Of Life'), ('eos', 'End Of Support')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_api_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='API guideline compliance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_api_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_api_guideline', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_api_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='API guildeine compliance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_fips_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='FIPS compliance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_fips_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_fips', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_fips_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='FIPS compliance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_gdpr_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='GDRP compliance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_gdpr_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_gdpr', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_gdpr_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='GDPR compliance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_commit_link',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Commit link', null=True),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_docs',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Documentation entry page', null=True),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_public_docs',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Documentation entry page', null=True),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_public_repo',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Repository', null=True),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_anonymisation_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='HTTP tracing notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_anonymisation_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_anonymisation', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_anonymisation_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='HTTP tracing acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_http_tracing_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='HTTP tracing notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_http_tracing_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_http_tracing', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_http_tracing_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='HTTP tracing acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_format_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Logging format acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_format_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_logging_format', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_format_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Logging format acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_storage_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Logging storage acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_storage_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_logging_storage', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_storage_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Logging storage acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sufficiency_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Logging sufficiency acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sufficiency_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_logging_sufficiency', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sufficiency_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Logging sufficiency acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_alerts_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Alerts guide acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_alerts_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_alerts', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_alerts_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Alerts guide acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_backup_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Backup capability acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_backup_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_backup', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_backup_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Backup capability acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_failover_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Failover capability acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_failover_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_failover', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_failover_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Failover capability acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_guide_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Operations guide capability acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_guide_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_op_guide', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_guide_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Operations guide capability acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Horizontal scalability capability acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_horizontal_scalability', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Horizontal scalability capability acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_metrics_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Monitoring metrics acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_metrics_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_metrics', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_metrics_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Monitoring metrics acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_scaling_guide_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Scaling guide acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_scaling_guide_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_scaling_guide', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_scaling_guide_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Scaling guide acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_sla_guide_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='SLA/SLO guide acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_sla_guide_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_sla_guide', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_sla_guide_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='SLA/SLO guide acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_zero_downtime_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Zero-downtime upgrade capability acceptance notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_zero_downtime_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_zero_downtime', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='op_zero_downtime_status',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Zero-downtime upgrade capability acceptance status', max_length=16),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_api_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='API tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_api_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_api_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='E2E tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_e2e_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Long-hault tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_longhaul_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_manual_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Manual tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_manual_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_manual_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_perf_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Perf tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_perf_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_perf_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_security_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Security tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_security_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_security_tests', to='panopticum.PersonModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_unit_tests_notes',
            field=panopticum.fields.SmartTextField(default='', help_text='Unit tests notes'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='qa_unit_tests_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_unit_tests', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentdataprivacyclassmodel',
            name='name',
            field=models.CharField(help_text='Data Access, Secrets Management, Sensitive Metadata, Non-sensitive Metadata', max_length=64),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_api_is_public',
            field=panopticum.fields.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='API is public', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Jenkins job to build the component', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_database',
            field=models.ManyToManyField(to='panopticum.DatabaseVendorModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_framework',
            field=models.ManyToManyField(to='panopticum.FrameworkModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_jira_component',
            field=panopticum.fields.SmartTextField(blank=True, help_text='JIRA component', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_language',
            field=models.ManyToManyField(to='panopticum.ProgrammingLanguageModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_logging',
            field=models.ManyToManyField(to='panopticum.LoggerModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_orm',
            field=models.ManyToManyField(to='panopticum.ORMModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_raml',
            field=panopticum.fields.SmartTextField(blank=True, help_text='RAML link', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_repo',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Repository', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='meta_update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_architect',
            field=models.ManyToManyField(related_name='architect_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_escalation_list',
            field=models.ManyToManyField(related_name='escalation_list_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_expert',
            field=models.ManyToManyField(related_name='expert_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_product_manager',
            field=models.ManyToManyField(related_name='product_manager_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_program_manager',
            field=models.ManyToManyField(related_name='program_managed_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_api_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='API tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='E2E tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='Long-haul tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_manual_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='Manual tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_perf_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='Performance tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_security_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='Security tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_unit_tests_quality',
            field=panopticum.fields.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('low', 'Low'), ('medium', 'Med'), ('high', 'High')], default='unknown', help_text='Unit tests quality', max_length=16),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='grafana',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Grafana link', null=True),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='info',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Info link', null=True),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='metrics',
            field=panopticum.fields.SmartTextField(blank=True, help_text='Metrics link', null=True),
        ),
        migrations.DeleteModel(
            name='ComponentLocationClassModel',
        ),
        migrations.DeleteModel(
            name='DeploymentTypeModel',
        ),
        migrations.DeleteModel(
            name='TestingModel',
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='component_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panopticum.ComponentVersionModel'),
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panopticum.DeploymentEnvironmentModel'),
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='location_class',
            field=models.ManyToManyField(to='panopticum.DeploymentLocationClassModel'),
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='open_ports',
            field=models.ManyToManyField(to='panopticum.TCPPortModel'),
        ),
        migrations.AddField(
            model_name='componentdependencymodel',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panopticum.ComponentModel'),
        ),
        migrations.AddField(
            model_name='componentdependencymodel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panopticum.ComponentVersionModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='_depends_on',
            field=models.ManyToManyField(related_name='dependee', through='panopticum.ComponentDependencyModel', to='panopticum.ComponentModel'),
        ),
        migrations.AddField(
            model_name='datacentermodel',
            name='components_deployments',
            field=models.ManyToManyField(to='panopticum.ComponentDeploymentModel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='components_deployments',
            field=models.ManyToManyField(to='panopticum.ComponentDeploymentModel'),
        ),
    ]
