# Generated by Django 2.1.15 on 2020-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0004_auto_20200322_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementset',
            name='doc_link',
            field=models.URLField(blank=True, max_length=4096, verbose_name='Documentation link URL'),
        ),
    ]
