# Generated by Django 2.1 on 2019-12-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0005_auto_20191227_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='_depends_on',
            new_name='depends_on',
        ),
    ]
