# Generated by Django 2.1.15 on 2020-03-22 20:25

from django.db import migrations
import panopticum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0005_requirementset_doc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_commit_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_jira_component',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_raml',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_commit_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_jira_component',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_public_docs',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_public_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_raml',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='dev_repo',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
    ]
