# Generated by Django 2.1.15 on 2020-04-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0005_auto_20200410_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentversionmodel',
            options={'ordering': ['-version'], 'permissions': [('experts_change', 'Component Experts can to change'), ('experts_delete', 'Component Experts can to delete'), ('qa_change', 'QA responsible an to change'), ('qa_delete', 'QA responsible an to delete'), ('program_manager_change', 'Can program manager to change'), ('program_manager_delete', 'Can program manager to delete'), ('product_manager_change', 'Can product manager to change'), ('product_manager_delete', 'Can product manager to delete'), ('escalation_list_change', 'Can persons in escalation list to change'), ('escalation_list_delete', 'Can persons in escalation list to delete'), ('architect_change', 'Can architect to change'), ('architect_delete', 'Can architect to delete')]},
        ),
    ]
