# Generated by Django 3.1.14 on 2024-03-10 23:01

from django.db import migrations, models
import django_atlassian.models.base
import django_atlassian.models.djira


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0006_auto_20200413_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=(models.Model, django_atlassian.models.djira.JiraIssueModel, django_atlassian.models.base.JiraModel),
        ),
        migrations.AlterModelOptions(
            name='historicalcomponentversionmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical component version model', 'verbose_name_plural': 'historical component version models'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequirementstatusentry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical requirement status entry', 'verbose_name_plural': 'historical requirement status entrys'},
        ),
        migrations.AlterField(
            model_name='componentdependencymodel',
            name='type',
            field=models.CharField(choices=[('strong_rw', 'Runtime - Strong - R/W'), ('strong_ro', 'Runtime - Strong - R/O'), ('strong_wo', 'Runtime - Strong - W/O'), ('weak_rw', 'Runtime - Weak - R/W'), ('weak_ro', 'Runtime - Weak - R/O'), ('weak_wo', 'Runtime - Weak - W/O'), ('compile_time', 'Compile time')], default='strong_rw', help_text="Compile time - Given component requires the other component statically and can't be compiled w/o it; Strong - component can't operate w/o the other being deployed and running; Weak - component require the other to unblock certain functionality, however still can work well w/o it; R/W - component reads data from the other OR modify state of another component; R/O - component reads data from the other, BUT doesn't modify state of another component; W/O - component doesn't get any data from the other, BUT can modify it's state;", max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcomponentversionmodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirementstatusentry',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
