# Generated by Django 2.1 on 2019-12-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0006_auto_20191227_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentmodel',
            name='life_status',
            field=models.CharField(blank=True, choices=[('unknown', '?'), ('new', 'New'), ('mature', 'Mature'), ('legacy', 'Legacy'), ('eol', 'End Of Life'), ('eos', 'End Of Support')], default='unknown', max_length=16, null=True),
        ),
    ]
