# Generated by Django 3.1.14 on 2024-03-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0007_auto_20240311_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticLinksCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilteredComponent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('panopticum.componentmodel',),
        ),
        migrations.CreateModel(
            name='StaticLinksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of link', max_length=128, unique=True)),
                ('url', models.URLField(max_length=2048)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_links')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panopticum.staticlinkscategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(blank=True, help_text='Link to service for example http://example.com', max_length=2048, null=True)),
                ('ignore_ssl', models.BooleanField(verbose_name='Ignore SSL certificate')),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panopticum.credential')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget', models.CharField(max_length=32, unique=True)),
                ('show_for_all_release_family', models.BooleanField(default=False, help_text='This flag overrides options selected in release family field')),
                ('release_family', models.ManyToManyField(blank=True, help_text='Show widget for components under these release families.', to='panopticum.ProductFamilyModel')),
            ],
        ),
        migrations.CreateModel(
            name='DocLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(help_text='Url for document', max_length=2048)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='panopticum.componentversionmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticum.doctype')),
            ],
            options={
                'unique_together': {('type', 'url', 'component_version')},
            },
        ),
    ]
