# Generated by Django 3.1.14 on 2024-03-13 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0008_componentwidget_credential_doclink_doctype_externalservice_filteredcomponent_staticlinkscategorymode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechradarQuadrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Top Right, Bottom Right, ...', max_length=64)),
                ('position', models.IntegerField(choices=[(0, 'Bottom Right'), (1, 'Bottom Left'), (2, 'Top Left'), (3, 'Top Right')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechradarRing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.IntegerField(choices=[(0, 'Inner'), (1, 'First'), (2, 'Second'), (3, 'Outer')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#e0e0e0', max_length=64, verbose_name='Color code: #000000')),
            ],
        ),
        migrations.CreateModel(
            name='TechradarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=64, verbose_name='Entry name')),
                ('description', models.TextField(blank=True, null=True)),
                ('moved', models.IntegerField(choices=[(0, 'Not moved'), (-1, 'Moved out'), (1, 'Moved in')], default=0, verbose_name='Short history tracking')),
                ('link', models.URLField(blank=True, max_length=4096, verbose_name='Entry link URL')),
                ('active', models.BooleanField(default=True)),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticum.techradarquadrant')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticum.techradarring')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTechradarEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=64, verbose_name='Entry name')),
                ('description', models.TextField(blank=True, null=True)),
                ('moved', models.IntegerField(choices=[(0, 'Not moved'), (-1, 'Moved out'), (1, 'Moved in')], default=0, verbose_name='Short history tracking')),
                ('link', models.URLField(blank=True, max_length=4096, verbose_name='Entry link URL')),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quadrant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panopticum.techradarquadrant')),
                ('ring', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='panopticum.techradarring')),
            ],
            options={
                'verbose_name': 'historical techradar entry',
                'verbose_name_plural': 'historical techradar entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
