# Generated by Django 2.1 on 2019-12-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0008_auto_20191227_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='op_anonymization_support',
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_database',
            field=models.ManyToManyField(blank=True, to='panopticum.DatabaseVendorModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_framework',
            field=models.ManyToManyField(blank=True, to='panopticum.FrameworkModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_language',
            field=models.ManyToManyField(blank=True, to='panopticum.ProgrammingLanguageModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_logging',
            field=models.ManyToManyField(blank=True, to='panopticum.LoggerModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_orm',
            field=models.ManyToManyField(blank=True, to='panopticum.ORMModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_delete',
            field=models.BooleanField(blank=True, help_text='Is it safe to delete?'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_redeploy',
            field=models.BooleanField(blank=True, help_text='Is it safe to redeploy?'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_restart',
            field=models.BooleanField(blank=True, help_text='Is it safe to restart?'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_architect',
            field=models.ManyToManyField(blank=True, related_name='architect_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_escalation_list',
            field=models.ManyToManyField(blank=True, related_name='escalation_list_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_expert',
            field=models.ManyToManyField(blank=True, related_name='expert_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_product_manager',
            field=models.ManyToManyField(blank=True, related_name='product_manager_of', to='panopticum.PersonModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='owner_program_manager',
            field=models.ManyToManyField(blank=True, related_name='program_managed_of', to='panopticum.PersonModel'),
        ),
    ]
