# Generated by Django 2.1 on 2019-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0009_auto_20191227_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_delete',
            field=models.BooleanField(blank=True, help_text='Is it safe to delete?', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_redeploy',
            field=models.BooleanField(blank=True, help_text='Is it safe to redeploy?', null=True),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_safe_restart',
            field=models.BooleanField(blank=True, help_text='Is it safe to restart?', null=True),
        ),
    ]
