# Generated by Django 4.2.11 on 2024-04-06 10:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0009_historicaltechradarentry_techradarentry_techradarquadrant_techradarring'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechRadarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Section order')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Custom HTML text representing a Technology Radar details section')),
            ],
        ),
        migrations.AlterField(
            model_name='componentdependencymodel',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticum.componentmodel'),
        ),
        migrations.AlterField(
            model_name='componentdependencymodel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panopticum.componentversionmodel'),
        ),
        migrations.AlterField(
            model_name='componentdeploymentmodel',
            name='component_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='panopticum.componentversionmodel'),
        ),
    ]
