# Generated by Django 2.1 on 2019-12-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0011_auto_20191227_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='meta_profile_completion',
            new_name='meta_profile_completeness',
        ),
    ]
