# Generated by Django 4.2.11 on 2024-04-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0011_componentversionmodel_excluded_requirement_set_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='meta_bad_rating_fields',
            new_name='meta_profile_not_signed_requirements',
        ),
        migrations.RenameField(
            model_name='historicalcomponentversionmodel',
            old_name='meta_bad_rating_fields',
            new_name='meta_profile_not_signed_requirements',
        ),
    ]
