# Generated by Django 2.1 on 2019-12-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0012_auto_20191227_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='meta_profile_not_filled_fields',
            field=models.TextField(default=''),
        ),
    ]
