# Generated by Django 2.1 on 2019-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0013_componentversionmodel_meta_profile_not_filled_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='compliance_applicable',
            field=models.BooleanField(default=True, help_text='Compliance requirements applicable?'),
        ),
    ]
