# Generated by Django 4.2.11 on 2024-04-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0013_remove_componentversionmodel_meta_mt_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='dev_jira_component',
            new_name='dev_issuetracker_component',
        ),
        migrations.RenameField(
            model_name='historicalcomponentversionmodel',
            old_name='dev_jira_component',
            new_name='dev_issuetracker_component',
        ),
    ]
