# Generated by Django 4.2.11 on 2024-04-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0014_rename_dev_jira_component_componentversionmodel_dev_issuetracker_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementset',
            name='order',
            field=models.IntegerField(default=0, help_text='Sorting order in UI, 0 means hidden'),
        ),
    ]
