# Generated by Django 2.1 on 2019-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0014_componentversionmodel_compliance_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='meta_compliance_rating',
            field=models.IntegerField(default=0),
        ),
    ]
