# Generated by Django 2.1 on 2019-12-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0015_componentversionmodel_meta_compliance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='meta_bad_rating_fields',
            field=models.TextField(default=''),
        ),
    ]
