# Generated by Django 4.2.11 on 2024-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0015_requirementset_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementset',
            name='order',
        ),
        migrations.AddField(
            model_name='requirementset',
            name='ui_slot',
            field=models.IntegerField(default=0, help_text='Components view UI slot: 0 - hidden; 1-3 - middle screen part; 4-8 right screen part'),
        ),
    ]
