# Generated by Django 2.1 on 2019-12-28 14:48

from django.db import migrations
import django.db.models.deletion
import panopticum.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0016_componentversionmodel_meta_bad_rating_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='mt_logging_sufficiency_signoff',
            new_name='mt_logging_completeness_signoff',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='mt_anonymisation_notes',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='mt_anonymisation_signoff',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='mt_anonymisation_status',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='mt_logging_sufficiency_notes',
        ),
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='mt_logging_sufficiency_status',
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_db_anonymisation_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_db_anonymisation_signoff',
            field=panopticum.models.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_db_anonymisation', to='panopticum.PersonModel', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_db_anonymisation_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_completeness_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_completeness_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Are logs sufficient?', max_length=16, verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sanitization_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sanitization_signoff',
            field=panopticum.models.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_logggin_sanitization', to='panopticum.PersonModel', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='mt_logging_sanitization_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_api_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_api_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_fips_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_fips_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_gdpr_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='compliance_gdpr_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_api_is_public',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_build_jenkins_job',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_commit_link',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_docs',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_jira_component',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_docs',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_public_repo',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_raml',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='dev_repo',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_http_tracing_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_http_tracing_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='HTTP request b3 propagation support', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_logging_format_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_logging_format_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_logging_storage_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_logging_storage_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', help_text='Is proper logs storage used?', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_alerts_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_alerts_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_backup_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_backup_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_failover_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_failover_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_guide_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_guide_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_horizontal_scalability_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_metrics_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_metrics_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_scaling_guide_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_scaling_guide_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_sla_guide_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_sla_guide_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_zero_downtime_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='op_zero_downtime_status',
            field=panopticum.models.NoPartialYesField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('no', 'No'), ('partial', 'Partial'), ('yes', 'Yes')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_api_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_api_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_e2e_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_longhaul_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_manual_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_manual_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_perf_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_perf_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_security_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_security_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_unit_tests_notes',
            field=panopticum.models.MarkupField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='qa_unit_tests_quality',
            field=panopticum.models.LowMedHighField(choices=[('unknown', '?'), ('n/a', 'N/A'), ('none', 'None'), ('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='unknown', max_length=16, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='grafana',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='info',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='datacentermodel',
            name='metrics',
            field=panopticum.models.URLsField(blank=True, default='', max_length=2048, null=True, verbose_name=''),
        ),
    ]
