# Generated by Django 4.2.11 on 2024-04-21 00:01

from django.db import migrations, models
import panopticum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0016_remove_requirementset_order_requirementset_ui_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_code_kloc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Code KLOC (approx)'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_logs_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='dev_metrics_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcomponentversionmodel',
            name='dev_code_kloc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Code KLOC (approx)'),
        ),
        migrations.AddField(
            model_name='historicalcomponentversionmodel',
            name='dev_logs_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcomponentversionmodel',
            name='dev_metrics_link',
            field=panopticum.fields.SmartTextField(blank=True, default='', help_text='List of URLs separated by whitespace', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='requirementset',
            name='ui_slot',
            field=models.IntegerField(default=0, help_text='Components view UI slot: 0 - hidden; 1-4 - middle screen part; 5-9 right screen part'),
        ),
    ]
