# Generated by Django 2.1 on 2019-12-28 14:58

from django.db import migrations, models
import django.db.models.deletion
import panopticum.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0017_auto_20191228_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversionmodel',
            name='locations',
            field=models.ManyToManyField(related_name='component_versions', to='panopticum.DeploymentLocationClassModel'),
        ),
        migrations.AlterField(
            model_name='componentversionmodel',
            name='mt_logging_completeness_signoff',
            field=panopticum.fields.SigneeField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_logging_completeness', to='panopticum.PersonModel', verbose_name=''),
        ),
    ]
