# Generated by Django 2.1 on 2019-12-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0019_auto_20191230_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_anonymisation_tests_quality',
            new_name='qa_anonymisation_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_api_tests_quality',
            new_name='qa_api_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_e2e_tests_quality',
            new_name='qa_e2e_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_longhaul_tests_quality',
            new_name='qa_longhaul_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_manual_tests_quality',
            new_name='qa_manual_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_perf_tests_quality',
            new_name='qa_perf_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_security_tests_quality',
            new_name='qa_security_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_unit_tests_quality',
            new_name='qa_unit_tests_status',
        ),
        migrations.RenameField(
            model_name='componentversionmodel',
            old_name='qa_upgrade_tests_quality',
            new_name='qa_upgrade_tests_status',
        ),
    ]
