# Generated by Django 2.1 on 2020-01-04 22:18

from django.db import migrations
import panopticum.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0022_componentmodel_is_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdependencymodel',
            name='notes',
            field=panopticum.fields.SmartTextField(blank=True, default='', verbose_name=''),
        ),
    ]
