# Generated by Django 2.1 on 2020-01-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0023_componentdependencymodel_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentmodel',
            name='is_library',
        ),
    ]
