# Generated by Django 2.1 on 2020-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0024_remove_componentmodel_is_library'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='ProductVersionModel',
        ),
        migrations.AlterField(
            model_name='componentdependencymodel',
            name='type',
            field=models.CharField(choices=[('sync_rw', 'Sync R/W'), ('sync_ro', 'Sync R/O'), ('sync_wo', 'Sync W/O'), ('async_rw', 'Async R/W'), ('async_ro', 'Async R/O'), ('async_wo', 'Async W/O'), ('includes', 'Includes')], default='sync_rw', max_length=16),
        ),
    ]
