# Generated by Django 2.1 on 2020-01-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0025_auto_20200107_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversionmodel',
            name='components_deployments',
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='product_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='panopticum.ProductVersionModel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='componentdeploymentmodel',
            name='location_class',
        ),
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='location_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='panopticum.DeploymentLocationClassModel'),
            preserve_default=False,
        ),
    ]
