# Generated by Django 2.1 on 2020-01-08 09:34

from django.db import migrations, models
import panopticum.models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0026_auto_20200108_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdeploymentmodel',
            name='notes',
            field=panopticum.models.SmartTextField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='componentdeploymentmodel',
            name='name',
            field=models.CharField(blank=True, help_text='Component deployment name: Cloud Account Server', max_length=64),
        ),
        migrations.AlterField(
            model_name='componentdeploymentmodel',
            name='open_ports',
            field=models.ManyToManyField(blank=True, to='panopticum.TCPPortModel'),
        ),
    ]
