# Generated by Django 2.1 on 2020-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0027_auto_20200108_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversionmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='productversionmodel',
            name='fullname',
            field=models.CharField(blank=True, help_text='Product version full name', max_length=64),
        ),
        migrations.AddField(
            model_name='productversionmodel',
            name='shortname',
            field=models.CharField(blank=True, help_text='Product version short name', max_length=64),
        ),
        migrations.AlterField(
            model_name='componentdeploymentmodel',
            name='name',
            field=models.CharField(blank=True, help_text='Component deployment name: Cloud Account Server', max_length=64, verbose_name='Deployment name'),
        ),
    ]
