# Generated by Django 2.1 on 2020-01-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0028_auto_20200108_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversionmodel',
            name='fullname',
            field=models.CharField(help_text='Product version full name', max_length=64),
        ),
        migrations.AlterField(
            model_name='productversionmodel',
            name='shortname',
            field=models.CharField(help_text='Product version short name', max_length=64),
        ),
    ]
