# Generated by Django 2.1 on 2020-01-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0029_auto_20200108_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentversionmodel',
            name='locations',
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='meta_locations',
            field=models.ManyToManyField(blank=True, help_text='cached component deployment locations', related_name='component_versions', to='panopticum.DeploymentLocationClassModel'),
        ),
        migrations.AddField(
            model_name='componentversionmodel',
            name='meta_product_versions',
            field=models.ManyToManyField(blank=True, help_text='cached product versions', related_name='component_versions', to='panopticum.ProductVersionModel'),
        ),
    ]
