# Generated by Django 2.1 on 2020-01-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0030_auto_20200108_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productversionmodel',
            old_name='fullname',
            new_name='name',
        ),
    ]
