# Generated by Django 2.1 on 2020-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0032_auto_20200109_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentruntimetypemodel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='componentruntimetypemodel',
            name='order',
            field=models.IntegerField(default=1, help_text='sorting order'),
            preserve_default=False,
        ),
    ]
