# Generated by Django 2.1 on 2020-01-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panopticum', '0034_auto_20200109_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcpportmodel',
            options={'ordering': ['port']},
        ),
    ]
